language: python
install:
  - pip install -r requirements.txt
  - pip install tox
matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36

script:
  - tox -e $TOX_ENV

